### ISSUE TITLE
[Request] B:PlanetSkyOverride disabled for custom dims

### ISSUE THREAD

**Issue by BeYondZer** [Advanced-Rocketry/AdvancedRocketry#1687] opened 2019-09-01 22:23 UTC
When dimmapping custom dims so that you can travel to dimensions with the rocket, the skybox for those dims may not look like they are supposed to look.
If I travel to the twilight forest with a command for example, it looks like it should.
If I travel there with a rocket, then the skybox includes a sun, which normally isn't there.
Another example would be a dimension that isn't supposed to have stars, but it'll show stars if you travel there.
Would it be possible to allow per dimension PlanetSkyOverride settings?
That way it can be disabled for certain dimensions but not for others.

**Comment by voidsong-dragonfly** [comment] 2021-04-15 03:56
Duplicate of #1531

**Closed by voidsong-dragonfly** 2021-04-15 03:56 UTC
Labels: enhancement
