### ISSUE TITLE
Ingame Manual

### ISSUE THREAD

**Issue by CTH999** [Advanced-Rocketry/AdvancedRocketry#1368] opened 2018-08-03 15:37 UTC
I think it would help A lot if we had an ingame manual. However, that's just my thought!

**Comment by Jummit** [comment] 2018-09-30 10:10
Maybe a multiblock structure that gives you tips, for example a mission control building?

**Comment by CTH999** [comment] 2018-11-10 18:03
Tat would definatly be an interesting way to do a manual!

I like that Idea!

**Comment by voidsong-dragonfly** [comment] 2021-04-15 02:48
Duplicate of #66

**Closed by voidsong-dragonfly** 2021-04-15 02:48 UTC
Labels: enhancement
