### ISSUE TITLE
[Enhancement] Space Debris

### ISSUE THREAD

**Issue by brianvis** [Advanced-Rocketry/AdvancedRocketry#873] opened 2017-10-11 10:20 UTC
Space Debris that can hit your ship and Damage you. Would be a cool option for the next update!

**Comment by C1ffisme** [comment] 2017-10-11 16:37
I don't really like the idea of having to constantly upkeep my ship because the Random Generator said so.

**Comment by Divineaspect** [comment] 2017-10-11 17:51
It would be interesting, and a reason to upgrade your ship components over time.
Should definitely be toggleable, I'd turn it on, but I play on hard anyway.

**Comment by GhostedEmbers** [comment] 2017-10-18 03:12
Maybe a sort of defensive turret to shoot them would be a valid way to lower the need of constant upkeep, 
Essentially You'd need to automate ammo of some sort, or make a higher tier that can run off of electricity

**Comment by C1ffisme** [comment] 2017-10-18 04:09
Constant upkeep is only acceptable if it requires little thought and is easy to fix, such as Minecraft's hunger system. Getting hit with meteors and losing parts of the ship that you may not remember how to fix is not something I would find "fun" in any non-sarcastic definition of the word.

It's the reason why people on the Minecraft Forum don't like suggestions for Natural Disasters, or creepers with larger explosions. It's annoying, and takes time that the player could be spending on progressing or building.

**Comment by voidsong-dragonfly** [comment] 2021-04-15 02:44
Duplicate of #386

**Closed by voidsong-dragonfly** 2021-04-15 02:44 UTC
Labels: enhancement
