### ISSUE TITLE
[Request] OreDict support for multiblocks

### ISSUE THREAD

**Issue by JadianRadiator** [Advanced-Rocketry/AdvancedRocketry#1801] opened 2020-04-07 22:02 UTC
Please add OreDict support in multiblocks for the machine structure blocks.
This would allow modpack authors to set/use a block of their choice as the machine structure blocks for multiblocks.
This is the second time in history I've asked this.
The first time was back before the movement of items to libvulpes was done.
As it had been added after that first request.
iirc the additional tiers of motors had been added to libvulpes,
but back then the additional tiers hadn't been added to multiblock "recipes" at that time.

**Comment by Gliese-832-c** [comment] 2020-06-13 08:01
Yes, configurable multiblocks would be nice; it would allow modpack authors to balance the mod in consideration of other mods in the pack.

**Comment by voidsong-dragonfly** [comment] 2021-04-15 02:51
Duplicate of #395

**Closed by voidsong-dragonfly** 2021-04-15 02:51 UTC
Labels: enhancement
