### ISSUE TITLE
Satellite Terminal

### ISSUE THREAD

**Issue by WileyWolf142536** [Advanced-Rocketry/AdvancedRocketry#1280] opened 2018-05-04 16:36 UTC
## Version of Advanced Rocketry
[140-78 forge 14.23.3.2673]
## Have you verified this is an issue in the latest unstable build
Y,N, N/A
## Version of LibVulpes
[0.2.8-29]
## Version of Minecraft
[1.12.2]
## Crash report or log (if applicable)
http://prntscr.com/jdr1wz
http://prntscr.com/jdr26j
http://prntscr.com/jdr2fz

## Description of the problem
Hello, I have a problem with your mode (!
Problem in Satellite Terminal! When I open it, all the inventory disappears! Please correct this error!
Thank you!

**Comment by timstableford** [comment] 2018-07-15 09:19
I can confirm I see this issue too. My symptoms are as seen in the FTB issue referenced above. More of an inventory corruption that things disappearing

**Comment by ThatOneCheetah** [comment] 2018-11-01 20:12
Can confirm, satellite terminal glitches inventory.
Using InventoryTweak's sort button seems to fix it; however any satellite ID chips get unprogrammed in the progress.

**Comment by Coolguy3289** [comment] 2019-01-06 19:46
Adding to this issue, Here are crash logs from the client side:
https://paste.dimdev.org/ewuweyixin.mccrash

Once this bug occurs, I continually get crash dumps pouring into my console on the client.

**Comment by dmodoomsirius** [comment] 2019-03-04 00:12
Is this still a issue? Please comment if it is and i will reopen if if you are unable? We are closing old issues to see what is still relevant and needs to be fixed.

**Comment by Coolguy3289** [comment] 2019-03-04 06:13
@dmodoomsirius Yes, this is still an issue. That is why I commented adding to the issue a couple months ago, unless there was a code change that hasn't been pushed to the GitHub yet.

**Comment by timhuff** [comment] 2019-03-06 05:44
I'm on a server that's currently dealing with this issue.. @dmodoomsirius any update on what's going on here?

**Comment by timhuff** [comment] 2019-03-06 05:45
We have about 5 people on the server trying to launch our first rocket. No one can get this to work.

**Comment by ct-klein** [comment] 2019-08-18 18:02
Still happens
https://imgur.com/XJC1CXD

**Comment by zmaster587** [comment] 2019-08-19 02:19
@ct-klein I'm not sure how this relates to the issue, your inventory is still clearly there in the screenshot.

As a note, I am not able to replicate it still.  Is there something you're doing beyond opening the terminal?

![image](https://user-images.githubusercontent.com/3536685/63235095-2eaa0f00-c206-11e9-8aa8-55605ff59671.png)

**Comment by ct-klein** [comment] 2019-08-19 02:38
I didn't start with those satellite chips in my inventory.  They appeared, shoving everything else I have over and removing everything I have from the hotbar at the bottom.  Problem's been kicking around for over a year so I didn't realize I needed to be exacting in my wording.

No, I did nothing besides attempt to open the satellite terminal.  I wanted to put a data storage module chip into it, its in the 5th position of the hotbar that you cannot see.  If I open some chest or do a sort on my inventory things reappear. The only way I can access the terminal to do what I want is to take the satellite chip out and then break/replace the terminal.

**Comment by Coolguy3289** [comment] 2020-01-19 02:23
Bumping as this issue hasn't been addressed.

**Comment by SergeantTibbs** [comment] 2020-02-19 18:57
Hello,

I am also having issues with satellite terminals messing with my inventory.

On the left of this image you will see my inventory before opening the satellite terminal.  On the right is what my inventory looks like after I open the terminal.

![Inventory Screenshot 1](https://user-images.githubusercontent.com/36784819/74864967-41141b00-5305-11ea-8f42-55f67c8c67bd.jpg)

I had to break and replace the terminal to reset this, but then it would happen again after the first fresh use.  Upon closer look, you may notice that it has shifted my inventory down one and two to the right, eliminating my quick bar items and replacing them at the top with Satellite Chips.  This effect persists even after closing the Terminal, but is remedied by opening my backpack.

Playing Enigmatica2Expert-1.75 via MultiMC 5 - Version 0.6.8-1419

**Comment by dmodoomsirius** [comment] 2020-02-19 23:20
What is the version of advanced Rocketry and LibVulpes that you have? Have you tried with just advanced rocketry and LibVulpes? If it does not happen what is the minimal mods that you are able to test with that this issue occurs? 

The form that should have popped up would have asked you these questions. It will help us narrow down the possibility to see what is causing this. Try disabling a inventory tweaker mod first.

**Comment by zmaster587** [comment] 2020-02-20 04:24
also see https://github.com/zmaster587/AdvancedRocketry/issues/1298#issuecomment-588588007

**Comment by SergeantTibbs** [comment] 2020-02-24 03:58
Unfortunately I've been experiencing this on a server that is not under my control.  I will ask the host for more information to help you troubleshoot the issue.

**Comment by DemolitionDerby** [comment] 2020-05-11 01:01
Hi, I can confirm that this is still an issue

**Comment by zdubro** [comment] 2020-07-21 19:09
Latest E2E pack has this issue, as of today. Just hit it and wondered what happened to my inventory. I now dump all my inv items before opening the terminal out of fear of losing anything.

**Comment by rptbuddy** [comment] 2020-08-09 19:25
I'm playing FTB Interactions and am experiencing these issues.
![2020-08-09_11 34 19](https://user-images.githubusercontent.com/52925454/89740147-f8375680-da4b-11ea-8094-76b27428ebe2.png)
![2020-08-09_11 34 25](https://user-images.githubusercontent.com/52925454/89740151-fec5ce00-da4b-11ea-8f2b-3547c1d9e1bb.png)

Notice the error it keeps throwing in the top right.

Here is the crash log it creates for me.
https://pastebin.com/tF2nT0vZ

**Comment by thunder1410** [comment] 2020-08-25 20:48
I am also having the same issue in FTB interactions v.2.0.7.
I have noticed that when you place the machine it will work, until someone from the server else enters it from then on it will throw errors and screw over the inventory.
Advanced Rocketry version 1.7.0.-232
Vulpus library 0.4.2.-75
[crash.txt](https://github.com/zmaster587/AdvancedRocketry/files/5126215/crash.txt)

**Comment by Coolguy3289** [comment] 2020-11-02 08:22
Unless an update has been pushed, this is still an issue.

**Comment by greenlittleapple** [comment] 2020-12-02 17:10
Still an issue. I can't open a satellite terminal without it rearranging my inventory and/or making my items disappear until relogin

**Comment by falizure** [comment] 2020-12-04 18:01
same problem, ftb interactions 2.0.9 advanced rocketry 1.12.2-1.7.0-232-unversal, lib vulpes 1.12.2-0.4.2-76-universal
interacting with the satellite terminals spams my screen with unknown error messages and duplicates the ID chips into my inventory, and unlike what these guys are reporting it is actually not just hiding items until you move them it is physically creating them and deleting items from my inventory, i have tried sorting inventory i have tried dumping and requipping, even restarting the server itself, although after restarting the server it does stop doing it for a unknown period of time it does not recover my items or delete the excess chips, it also duplicated my time in a bottle as well. im also getting spammed with these crash reports 
[crash-2020-12-04_00.33.48-client.txt](https://github.com/zmaster587/AdvancedRocketry/files/5644519/crash-2020-12-04_00.33.48-client.txt)

**Comment by Crystal98TR** [comment] 2021-01-16 16:42
Still an issue. Really annoying and hard to do things on it.

**Comment by voidsong-dragonfly** [comment] 2021-03-18 02:47
Does this build fix it?
[AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip](https://github.com/zmaster587/AdvancedRocketry/files/6160951/AdvancedRocketry-1.12.2-1.7.0-universal.jar.zip)

**Comment by jedjoud10** [comment] 2021-05-24 03:35
Yup, still an issue. Currently playing in a LAN world with a few friends and it's bugged out

**Comment by voidsong-dragonfly** [comment] 2021-08-21 13:46
Fixed with 2.1.0

**Closed by voidsong-dragonfly** 2021-08-21 13:46 UTC
Labels: Unconfirmed Bug, MC 1.12.2, Exempt

**Comment by ct-klein** [comment] 2021-08-21 21:45
3 years... excellent!
