### ISSUE TITLE
[Request] Make the rocket launch key configurable, please.

### ISSUE THREAD

**Issue by Gliese-832-c** [Advanced-Rocketry/AdvancedRocketry#1939] opened 2020-10-12 15:23 UTC
I'd like to change the key that launches the rocket, but this seems to be impossible. Please add a way to change that.

**Comment by Gliese-832-c** [comment] 2020-10-12 15:48
Alternatively, prevent launching while in RCS mode.

**Comment by voidsong-dragonfly** [comment] 2021-04-03 23:57
Duplicate of #1014

**Closed by voidsong-dragonfly** 2021-04-03 23:57 UTC
Labels: enhancement
