### ISSUE TITLE
Performance issue with liquid conduits and reactor

### ISSUE THREAD

**Issue by Sir-Will** [Advanced-Rocketry/AdvancedRocketry#1915] opened 2020-09-15 18:10 UTC
If a conduit is filling the reactor the inventory updated is being run too often causing performance issues.

![](https://i.imgur.com/cJYsfsV.png)
![](https://i.imgur.com/YcMGW7M.png)

**Comment by Sir-Will** [comment] 2020-11-15 01:14
up

**Comment by Sir-Will** [comment] 2021-01-15 12:45
up

**Comment by voidsong-dragonfly** [comment] 2021-03-20 04:56
If I had to guess, the reason that this is taking a while is that the recipe list is extensively long - can you give a report on how long it takes in a pack with fewer armors?

**Comment by voidsong-dragonfly** [comment] 2021-04-15 03:54
Duplicate of #1595

**Closed by voidsong-dragonfly** 2021-04-15 03:54 UTC
Labels: Unconfirmed Bug
