### ISSUE TITLE
[Request] Multiple Galaxies

### ISSUE THREAD

**Issue by Husky009fromDiscord** [Advanced-Rocketry/AdvancedRocketry#1917] opened 2020-09-17 13:19 UTC
Hi, it's me, Husky009 from Discord.
As the title says, I (and Avalance7, credit to him) request the ability to have multiple galaxies in one world. 
This would be done by adding another tag to the planetDefs.xml file, the universe tag. It would contain the already existing galaxy tags, which contain the star tags, and so on.
Also the galaxy tag would get some new arguments similar to star arguments, namely name, numStars for randomly generating galaxies, x and y, and either size or customIcon (or both).
I've included an example for how the file would look down below.
[ExampleGalaxies.txt](https://github.com/zmaster587/AdvancedRocketry/files/5239323/ExampleGalaxies.txt)

**Comment by vizthex123** [comment] 2020-09-24 06:51
That sounds really cool, hope it gets added.

**Comment by Gliese-832-c** [comment] 2020-10-12 15:22
You could technically have the stars be defined using radial coordinates.

**Comment by voidsong-dragonfly** [comment] 2021-04-15 14:47
Duplicate of #1099

**Closed by voidsong-dragonfly** 2021-04-15 14:47 UTC
Labels: enhancement
