### ISSUE TITLE
[Request] Rocket sound on arrive and take off

### ISSUE THREAD

**Issue by mrgreaper** [Advanced-Rocketry/AdvancedRocketry#1942] opened 2020-10-15 16:02 UTC
**What do you think is missing or what do you think can be done better**
[Describe in detail what you want to see and how it makes the mod better]
Launching rockets from my control tower looks cool but there is no sound to the rocket unless almost ontop of it and even then its so quiet. 
You want to hear the sound of the rockets firing on the way up and the sound of the retro thrusters cutting in as it descends.

**Comment by voidsong-dragonfly** [comment] 2021-04-14 19:49
Duplicate of #474

**Closed by voidsong-dragonfly** 2021-04-14 19:49 UTC
Labels: enhancement
